-- SQLite
INSERT INTO VOTE(client_id, upvote, created)
  SELECT CASE WHEN RANDOM() < 0 THEN 1 ELSE 2 END, CASE WHEN RANDOM() < 100000 THEN 1 ELSE 0 END, 
  DATE('NOW', CAST(ABS(RANDOM()) % 60-30 AS VARCHAR(4)) || ' day')
  
   FROM (SELECT * FROM (
         (SELECT 0 UNION ALL SELECT 1) t2, 
         (SELECT 0 UNION ALL SELECT 1) t4,
         (SELECT 0 UNION ALL SELECT 1) t8,
         (SELECT 0 UNION ALL SELECT 1) t16,
         (SELECT 0 UNION ALL SELECT 1) t32,
         (SELECT 0 UNION ALL SELECT 1) t64,
         (SELECT 0 UNION ALL SELECT 1) t128,
         (SELECT 0 UNION ALL SELECT 1) t256,
         (SELECT 0 UNION ALL SELECT 1) t512,
         (SELECT 0 UNION ALL SELECT 1) t1024,
         (SELECT 0 UNION ALL SELECT 1) t2048
         )
    ) LIMIT 5000;