"""clients table

Revision ID: c1f12c0ad3ca
Revises:
Create Date: 2021-06-22 00:21:03.987747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c1f12c0ad3ca"
down_revision = None
branch_labels = None
depends_on = None


def downgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("client")

    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client",
        sa.Column("client_id", sa.INTEGER(), nullable=True),
        sa.Column("client", sa.TEXT(), nullable=False),
        sa.Column("token", sa.TEXT(), nullable=False),
        sa.Column("token_start", sa.CHAR(length=3), nullable=False),
        sa.Column("location_id", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("client_id"),
        sa.UniqueConstraint("client"),
    )
    # ### end Alembic commands ###
